### ISSUE TITLE
The parameter of shape and scale become NaN 

### ISSUE THREAD

**Issue by JiangWatson** [autonlab/auton-survival#107]
hello, I use to DeepRecurrentSurvivalMachines to model the staying length in ICU, the parameter of shape and scale become NaN after the first back propagation. how to deal with input data?

**Comment by chiragnagpal** [comment]
are you sure there are no nans in the input or the labels?

**Comment by JiangWatson** [comment]
Thanks for your reply! I have fixed the problem. There is a zero value in survival time.

**Comment by chiragnagpal** [comment]
great,  Thank you 👍 :)
