### ISSUE TITLE
Predict Score Function for Deep Cox Mixtures (PyTorch Implementation)

### ISSUE THREAD

**Issue by PranavM98** [autonlab/auton-survival#62]
Hi! Really inspired by this work and tried to implement the DCM model in our project. Noticed that there was a predict_scores function in the tensorflow implementation of dcm but unable to find the same function in PyTorch. Would really appreciate your help here. 
Thank you!

**Comment by chiragnagpal** [comment]
Hi @PranavM98 in survival analysis there are various different notions of "score" or "risk". The most common ones are: 

*Probability of Survival* $P(T>t|X=x)$ which you can get from the `predict_survival` function. 
*Risk of Event* $P(T<t|X=x)$ which is just an inverse of *Probability of Survival* and so $P(T<t|X=x)=1-P(T>t|X=x)$

**Comment by PranavM98** [comment]
Thank you for the explanation!
