### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by gdupret** [autonlab/auton-survival#78]
on https://autonlab.github.io/auton-survival/, installation instructions are:

foo@bar:~$ git clone https://github.com/autonlab/auton_survival
foo@bar:~$ pip install -r requirements.txt

It should be https://github.com/autonlab/auton-survival

**Comment by PotosnakW** [comment]
Hi @gdupret, thank you for raising this issue. It's fixed now. 

If you have any questions on the auton-survival package, please feel free to reach out to @chiragnagpal and I.
