### ISSUE TITLE
DSM / SUPPORT - Paper Results

### ISSUE THREAD

**Issue by ketencimert** [autonlab/auton-survival#83]
Hi!

Thanks for creating this great repo with such clean code and documentation! It has been very helpful with understanding the papers, building benchmarks, and using nice survival datasets, easily!

Got a question about DSM / SUPPORT dataset: I've been using your code to reproduce the results of https://arxiv.org/pdf/2003.01176.pdf, but the scores that I get (on C-index, Brier, etc..) are a little different than the paper. I would appreciate any help/tip (preprocessing, model usage - hyperparameters, etc..)!

Best!

**Comment by chiragnagpal** [comment]
Hi @ketencimert ! Thanks for the kind words! 

I just confirmed with my coauthor on the DSM paper, the SUPPORT dataset we used in the experiments for that paper is the one that was used by the original DeepSurv paper, you can find a copy of this dataset in their code repository here:
https://github.com/jaredleekatzman/DeepSurv/blob/master/experiments/data/support/support_train_test.h5

**Comment by ketencimert** [comment]
Thank you very much @chiragnagpal - I appreciate all the help. Best wishes and thanks for this great work again.
