### ISSUE TITLE
metrics.py indexes problem

### ISSUE THREAD

**Issue by AtzeniMichele** [autonlab/auton-survival#89]
Hi, 
I am using your package for the development of a dcph model. In order to see the performances on a validation set, I call the functions from metrics.py; as an example: 

```
brier = survival_regression_metric('brs', outcomes = validation_outcome,
                                      predictions = out_survival,
                                      times=times, outcomes_train=training_outcome)
```

However, it throws me the following error: 

  _File "/Users/micheleatzeni/PycharmProjects/brainteaser/auton-survival/auton_survival/metrics.py", line 235, in survival_regression_metric
    return _metric(survival_train, survival_test, predictions, times)
  File "/Users/micheleatzeni/PycharmProjects/brainteaser/auton-survival/auton_survival/metrics.py", line 265, in _cumulative_dynamic_auc
    return metrics.cumulative_dynamic_auc(survival_train, survival_test[idx], 1-predictions[idx], times)[0]
IndexError: index 628 is out of bounds for axis 0 with size 628_

Since python lists as well as numpy arrays are 0-based, the largest index in an array of size 628 would be 627.
So looking at the specific metrics.py functions, I think the possible problem is in the return statement (idx): 

```
def _brier_score(survival_train, survival_test, predictions, times, random_seed=None):

  idx = np.arange(len(predictions))
  if random_seed is not None:
    np.random.seed(random_seed)
    idx = np.random.choice(idx, len(predictions), replace=True)

  return metrics.brier_score(survival_train, survival_test[idx], predictions[idx], times)[-1]
```

It should be idx-1?

**Comment by AtzeniMichele** [comment]
prediction is (629, 9)
survival_test is (628,)

**Comment by chiragnagpal** [comment]
Your predictions size should match the survival_test size exactly

**Comment by AtzeniMichele** [comment]
Thanks. I checked and my outcome input to survival_regression_metric is correct (628, [event, time]). 
I suppose that the bug is in util.Surv.from_dataframe('event', 'time', outcomes)
