### ISSUE TITLE
what is "uncensored time control" and "uncensored time treated"

### ISSUE THREAD

**Issue by zapaishchykova** [autonlab/auton-survival#99]
Hi there! Thanks for the great repo!
I have a q: what are "uncensored time control" and "uncensored time treated" in the CMHE notebook example in the outcomes df and how to derive them? Thanks! https://nbviewer.org/github/autonlab/auton-survival/blob/master/examples/Demo%20of%20CMHE%20on%20Synthetic%20Data.ipynb

**Comment by chiragnagpal** [comment]
The data is generated synthetically. So we have access to the true outcome as well as the counterfactual outcome. 

Uncensored Time Control refers to the True Outcome if there was no censoring and no intervention was performed.

Uncensored Time Treated refers to the True Outcome if there was no censoring and an intervention was performed.

**Comment by zapaishchykova** [comment]
How about a real-world dataset, is there a way to compute these two variables?
